### ISSUE TITLE
Issue related to get_node_membership_node

### ISSUE THREAD

**Issue by jlhanson5** [dPys/PyNets#139]
* PyNets version: 0.5.81
* Python version: 3.6.3 (though 2.7 also installed)
* Operating System: Ubuntu 16.04.4

### Description

Trying to run Example B with preprocessed data. I can execute Example A without issue, but keeping running into errors (which may be nipype-related; also issues related to filetype of SMALLREF2mm.nii.gz). 

### What I Did

Initial command--
```
pynets_run.py -i /home/jamielh/Volumes/Hanson/NKI_HealthyBrainNetwork/SI/R1/derivatives/fmriprep/sub-NDARAA536PTU/func/test/sub-NDARAA536PTU_task-resting_bold_space-MNI152NLin2009cAsym_variant-smoothAROMAnonaggr_preproc.nii.gz -id NDARAA536PTU_temp -a coords_dosenbach_2010,coords_power_2011 -n Default -dt -thr 0.3 -ns 2,4 -mod partcorr,sps -plt
```
Output-- 
`------------------------------------------------------------------------

SUBJECT ID: NDARAA536PTU_temp
Iterating across multiple nilearn atlases...
Using RSN pipeline for: Default
Growing spherical nodes across multiple radius sizes: 2, 4...
Running functional connectometry only...
Functional file: /home/jamielh/Volumes/Hanson/NKI_HealthyBrainNetwork/SI/R1/derivatives/fmriprep/sub-NDARAA536PTU/func/test/sub-NDARAA536PTU_task-resting_bold_space-MNI152NLin2009cAsym_variant-smoothAROMAnonaggr_preproc.nii.gz

-------------------------------------------------------------------------

Running with {'n_procs': 2, 'memory_gb': 4}

181002-14:48:58,227 nipype.workflow INFO:
	 Workflow PyNets_NDARAA536PTU_temp settings: ['check', 'execution', 'logging', 'monitoring']
181002-14:48:58,337 nipype.workflow INFO:
	 Running in parallel.
181002-14:48:58,341 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 1 jobs ready. Free memory (GB): 4.00/4.00, Free processors: 2/2.
181002-14:48:58,512 nipype.workflow INFO:
	 [Node] Setting-up "PyNets_NDARAA536PTU_temp.imp_est" in "/tmp/tmpksfjm8bv/PyNets_NDARAA536PTU_temp/imp_est".
181002-14:48:58,522 nipype.workflow INFO:
	 [Node] Running "imp_est" ("nipype.interfaces.utility.wrappers.Function")
181002-14:48:58,679 nipype.workflow INFO:
	 Workflow meta settings: ['check', 'execution', 'logging', 'monitoring']
181002-14:48:58,747 nipype.workflow INFO:
	 Running in parallel.
181002-14:48:58,752 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 2 jobs ready. Free memory (GB): 4.00/4.00, Free processors: 2/2.
181002-14:48:58,852 nipype.workflow INFO:
	 [Node] Setting-up "meta.rsn_functional_connectometry.RSN_fetch_nodes_and_labels_node" in "/tmp/tmpq71683rv/meta/rsn_functional_connectometry/_atlas_select_coords_power_2011/RSN_fetch_nodes_and_labels_node".
181002-14:48:58,854 nipype.workflow INFO:
	 [Node] Setting-up "meta.rsn_functional_connectometry.RSN_fetch_nodes_and_labels_node" in "/tmp/tmpf42uq49a/meta/rsn_functional_connectometry/_atlas_select_coords_dosenbach_2010/RSN_fetch_nodes_and_labels_node".
181002-14:48:58,858 nipype.workflow INFO:
	 [Node] Running "RSN_fetch_nodes_and_labels_node" ("nipype.interfaces.utility.wrappers.Function")
181002-14:48:58,860 nipype.workflow INFO:
	 [Node] Running "RSN_fetch_nodes_and_labels_node" ("nipype.interfaces.utility.wrappers.Function")
Fetching coordinates and labels from nilearn coordinate-based atlases
Fetching coordinates and labels from nilearn coordinate-based atlases

Power 2011 atlas comes with dict_keys(['rois', 'description'])

Stacked atlas coordinates in array of shape (264, 3).

Dosenbach 2010 atlas comes with dict_keys(['rois', 'labels', 'networks', 'description'])

Stacked atlas coordinates in array of shape (160, 3).

181002-14:48:59,590 nipype.workflow INFO:
	 [Node] Finished "meta.rsn_functional_connectometry.RSN_fetch_nodes_and_labels_node".
181002-14:48:59,593 nipype.workflow INFO:
	 [Node] Finished "meta.rsn_functional_connectometry.RSN_fetch_nodes_and_labels_node".
181002-14:49:00,345 nipype.workflow INFO:
	 [MultiProc] Running 1 tasks, and 0 jobs ready. Free memory (GB): 3.80/4.00, Free processors: 1/2.
                     Currently running:
                       * PyNets_NDARAA536PTU_temp.imp_est
181002-14:49:00,755 nipype.workflow INFO:
	 [Job 0] Completed (meta.rsn_functional_connectometry.RSN_fetch_nodes_and_labels_node).
181002-14:49:00,758 nipype.workflow INFO:
	 [Job 18] Completed (meta.rsn_functional_connectometry.RSN_fetch_nodes_and_labels_node).
181002-14:49:00,761 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 2 jobs ready. Free memory (GB): 4.00/4.00, Free processors: 2/2.
181002-14:49:00,966 nipype.workflow INFO:
	 [Node] Setting-up "meta.rsn_functional_connectometry.get_node_membership_node" in "/tmp/tmpkk_w66py/meta/rsn_functional_connectometry/_atlas_select_coords_power_2011/get_node_membership_node".
181002-14:49:00,994 nipype.workflow INFO:
	 [Node] Setting-up "meta.rsn_functional_connectometry.get_node_membership_node" in "/tmp/tmpq2h6b2ph/meta/rsn_functional_connectometry/_atlas_select_coords_dosenbach_2010/get_node_membership_node".
181002-14:49:01,6 nipype.workflow INFO:
	 [Node] Running "get_node_membership_node" ("nipype.interfaces.utility.wrappers.Function")
181002-14:49:01,22 nipype.workflow INFO:
	 [Node] Running "get_node_membership_node" ("nipype.interfaces.utility.wrappers.Function")
181002-14:49:01,46 nipype.workflow WARNING:
	 [Node] Error on "meta.rsn_functional_connectometry.get_node_membership_node" (/tmp/tmpkk_w66py/meta/rsn_functional_connectometry/_atlas_select_coords_power_2011/get_node_membership_node)
181002-14:49:01,60 nipype.workflow WARNING:
	 [Node] Error on "meta.rsn_functional_connectometry.get_node_membership_node" (/tmp/tmpq2h6b2ph/meta/rsn_functional_connectometry/_atlas_select_coords_dosenbach_2010/get_node_membership_node)
181002-14:49:02,760 nipype.workflow ERROR:
	 Node get_node_membership_node.c1 failed to run on host pfc.
181002-14:49:02,760 nipype.workflow ERROR:
	 Saving crash info to /home/jamielh/Volumes/Hanson/Neuroimaging_Resources/crash-20181002-144902-jamielh-get_node_membership_node.c1-ebe143cf-6b06-4bbb-a576-b1a20fceeb1f.pklz
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/lib/python3.6/dist-packages/nipype/interfaces/base/core.py", line 522, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/lib/python3.6/dist-packages/nipype/interfaces/utility/wrappers.py", line 144, in _run_interface
    out = function_handle(**args)
  File "<string>", line 48, in get_node_membership
  File "/usr/local/lib/python3.6/dist-packages/nibabel/loadsave.py", line 53, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/home/jamielh/anaconda3/lib/python3.6/site-packages/pynets-0.5.81-py3.6.egg/pynets/rsnrefs/SMALLREF2mm.nii.gz"

181002-14:49:02,785 nipype.workflow ERROR:
	 Node get_node_membership_node.c0 failed to run on host pfc.
181002-14:49:02,786 nipype.workflow ERROR:
	 Saving crash info to /home/jamielh/Volumes/Hanson/Neuroimaging_Resources/crash-20181002-144902-jamielh-get_node_membership_node.c0-2eda193e-33f2-4944-aae0-5abd1fdab84e.pklz
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/lib/python3.6/dist-packages/nipype/interfaces/base/core.py", line 522, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/lib/python3.6/dist-packages/nipype/interfaces/utility/wrappers.py", line 144, in _run_interface
    out = function_handle(**args)
  File "<string>", line 48, in get_node_membership
  File "/usr/local/lib/python3.6/dist-packages/nibabel/loadsave.py", line 53, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/home/jamielh/anaconda3/lib/python3.6/site-packages/pynets-0.5.81-py3.6.egg/pynets/rsnrefs/SMALLREF2mm.nii.gz"

181002-14:49:02,806 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 0 jobs ready. Free memory (GB): 4.00/4.00, Free processors: 2/2.
181002-14:49:04,757 nipype.workflow INFO:
	 ***********************************
181002-14:49:04,757 nipype.workflow ERROR:
	 could not run node: meta.rsn_functional_connectometry.get_node_membership_node.c1
181002-14:49:04,757 nipype.workflow INFO:
	 crashfile: /home/jamielh/Volumes/Hanson/Neuroimaging_Resources/crash-20181002-144902-jamielh-get_node_membership_node.c1-ebe143cf-6b06-4bbb-a576-b1a20fceeb1f.pklz
181002-14:49:04,757 nipype.workflow ERROR:
	 could not run node: meta.rsn_functional_connectometry.get_node_membership_node.c0
181002-14:49:04,757 nipype.workflow INFO:
	 crashfile: /home/jamielh/Volumes/Hanson/Neuroimaging_Resources/crash-20181002-144902-jamielh-get_node_membership_node.c0-2eda193e-33f2-4944-aae0-5abd1fdab84e.pklz
181002-14:49:04,757 nipype.workflow INFO:
	 ***********************************
181002-14:49:04,763 nipype.workflow WARNING:
	 [Node] Error on "PyNets_NDARAA536PTU_temp.imp_est" (/tmp/tmpksfjm8bv/PyNets_NDARAA536PTU_temp/imp_est)
181002-14:49:06,352 nipype.workflow ERROR:
	 Node imp_est failed to run on host pfc.
181002-14:49:06,359 nipype.workflow ERROR:
	 Saving crash info to /home/jamielh/Volumes/Hanson/Neuroimaging_Resources/crash-20181002-144906-jamielh-imp_est-9b01a0ed-8c7c-4445-983f-c75bb53f2b78.pklz
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/lib/python3.6/dist-packages/nipype/interfaces/base/core.py", line 522, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/lib/python3.6/dist-packages/nipype/interfaces/utility/wrappers.py", line 144, in _run_interface
    out = function_handle(**args)
  File "<string>", line 106, in workflow_selector
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/plugins/base.py", line 192, in run
    report_nodes_not_run(notrun)
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/plugins/tools.py", line 82, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details

181002-14:49:06,382 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 0 jobs ready. Free memory (GB): 4.00/4.00, Free processors: 2/2.
181002-14:49:08,350 nipype.workflow INFO:
	 ***********************************
181002-14:49:08,350 nipype.workflow ERROR:
	 could not run node: PyNets_NDARAA536PTU_temp.imp_est
181002-14:49:08,350 nipype.workflow INFO:
	 crashfile: /home/jamielh/Volumes/Hanson/Neuroimaging_Resources/crash-20181002-144906-jamielh-imp_est-9b01a0ed-8c7c-4445-983f-c75bb53f2b78.pklz
181002-14:49:08,350 nipype.workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "/home/jamielh/anaconda3/bin/pynets_run.py", line 4, in <module>
    __import__('pkg_resources').run_script('pynets==0.5.81', 'pynets_run.py')
  File "/home/jamielh/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/jamielh/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/home/jamielh/anaconda3/lib/python3.6/site-packages/pynets-0.5.81-py3.6.egg/EGG-INFO/scripts/pynets_run.py", line 1034, in <module>
    wf.run(plugin='MultiProc', plugin_args=plugin_args)
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/engine/workflows.py", line 595, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/plugins/base.py", line 192, in run
    report_nodes_not_run(notrun)
  File "/usr/local/lib/python3.6/dist-packages/nipype/pipeline/plugins/tools.py", line 82, in report_nodes_not_run
    raise RuntimeError(('Workflow did not execute cleanly. '
RuntimeError: Workflow did not execute cleanly. Check log for details`

Crash files uploaded [Here](https://www.dropbox.com/s/eqvs43guu7wehb4/crash-20181002-144902-jamielh-get_node_membership_node.c0-2eda193e-33f2-4944-aae0-5abd1fdab84e.pklz?dl=0
) and [Here](https://www.dropbox.com/s/d1w9rzep6gx6o3d/crash-20181002-144906-jamielh-imp_est-9b01a0ed-8c7c-4445-983f-c75bb53f2b78.pklz?dl=0
) and [Here](https://www.dropbox.com/s/txhr74vvogd05pt/crash-20181002-144902-jamielh-get_node_membership_node.c1-ebe143cf-6b06-4bbb-a576-b1a20fceeb1f.pklz?dl=0
).

I've tried to update nibabel, nilearn, and nipype (but still run into those errors). Also, I run pytest and it seemed fine (but I might have execute incorrect syntax... output below--

`jamielh@pfc:~/Volumes/Hanson/Neuroimaging_Resources$ pytest
============================================================================================================================================ test session starts =============================================================================================================================================
platform linux -- Python 3.6.3, pytest-3.3.1, py-1.5.2, pluggy-0.6.0
rootdir: /home/jamielh/Volumes/Hanson/Neuroimaging_Resources, inifile:
plugins: xdist-1.23.2, forked-0.2, cov-2.6.0
collected 0 items

======================================================================================================================================== no tests ran in 4.79 seconds ========================================================================================================================================
jamielh@pfc:~/Volumes/Hanson/Neuroimaging_Resources$`

Thoughts on way to troubleshoot? (I was at least excited that Example A executed pretty quickly and easily for me... which was an improvement from previous test-drives for me!). 

Thanks much,
Jamie.

**Comment by jlhanson5** [comment]
I used PyPi/pip. I'll reinstall now and see if I run into issues.
Thanks much!

**Comment by jlhanson5** [comment]
SWEEEEEEET! Good to go! Thanks for the help (I'm SUPER excited to get "Net-ing").

![ndaraa536ptu_temp_coords_dosenbach_2010_partcorr_default_0 3_2mm_nosm_func_glass_viz](https://user-images.githubusercontent.com/7240261/46416717-161c2d80-c6f6-11e8-8c32-3b9a2150e1f0.png)
